config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tasks
  resources :user_sessions
  root to: "tasks#main"

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_list
  has_many :tasks

  scope :active, ->{ where(archived_at: nil).order(:position) }
  scope :archived, ->{ where.not(archived_at: nil).order(:position) }

  def archived
    !!archived_at
  end

  def archived=(b)
    if b == "1"
      self.archived_at = Time.now
    else
      self.archived_at = nil
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, optional: true
  has_one :next_task, class_name: 'Task', foreign_key: :next_task_id

  enum interval_type: {
    every_n_days: 0,
    n_days_after: 1,
    day_of_week:  2,
    day_of_month: 3,
    day_of_year:  4,
  }

  validates :title, presence: true
  validates :project, presence: true, if: ->{ project_id != nil }
  validates :interval_value, presence: true, if: ->{ interval_type != nil }
  validates :interval_value, numericality: { greater_than_or_equal_to: 1 }, if: ->{ interval_type == "n_days" }
  validates :interval_value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 6 }, if: ->{ interval_type == "day_of_week" }
  validates :interval_value, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 31 }, if: ->{ interval_type == "day_of_month" }
  validates :interval_value, numericality: { greater_than_or_equal_to: 101, less_than_or_equal_to: 1231 }, if: ->{ interval_type == "day_of_year" }

  before_update :create_next_task

  scope :done, ->{ where(done: true) }
  scope :undone, ->{ where(done: false) }

  private

  # Create next task if interval_type is set
  def create_next_task
    return if !self.done || self.interval_type.nil?
    self.next_task = Task.create!(title: self.title,
                                  done: false,
                                  due_date: next_due_date(Date.today),
                                  project_id: self.project_id,
                                  interval_type: self.interval_type,
                                  interval_value: self.interval_value)
  end

  def next_due_date(today)
    case interval_type
    when "every_n_days"
      return (self.due_date || today) + interval_value
    when "n_days_after"
      return today + interval_value
    when "day_of_week"
      dw = %i(sunday monday tuesday wednesday thursday friday saturday)[interval_value]
      return today.next_occurring(dw)
    when "day_of_month"
      the_day = Date.new(today.year, today.month, interval_value)
      if the_day > today
        return the_day
      else
        return the_day.next_month
      end
    when "day_of_year"
      the_day = Date.new(today.year, interval_value / 100, interval_value % 100)
      if the_day > today
        return the_day
      else
        return the_day.next_year
      end
    else
      raise "invalid interval_type: #{interval_type.inspect}"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @active_projects = Project.active
    respond_to do |format|
      format.html { @archived_projects = Project.archived }
      format.json {}
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :archived)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Pagy::Backend
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def main
    @no_header = true
  end

  # GET /tasks
  # GET /tasks.json
  def index
    query = Task.all
    case params[:done]
    when "0"
      query = query.where(done: false)
    when "1"
      query = query.where(done: true)
    end
    case params[:sort]
    when "updated_at"
      query = query.order(updated_at: :desc)
    when "due_date"
      query = query.order(due_date: :desc)
    end
    respond_to do |format|
      format.html { @pagy, @tasks = pagy(query) }
      format.json { @tasks = query.all }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(
        :title, :done, :due_date, :project_id, :interval_type, :interval_value
      )
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vision</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env == "development" %>
      <style>h1{ background: orange; }</style>
    <% end %>
  </head>

  <body>
    <% unless @no_header %>
      <h1><a href='/'>Vision</a></h1>
    <% end %>
    <div>
      <% [:notice, :alert].each do |key| %>
        <% if flash[key] %>
          <p id="flash_<%= key %>">
            <span onclick="document.querySelector('#flash_<%= key %>').style.display = 'none'">
              [x]
            </span>
            <%= flash[key] %>
          </p>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :archived %>
    <%= form.check_box :archived %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Active Projects</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_projects.each do |project| %>
      <tr>
        <td><%= project.position %></td>
        <td><%= project.title %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

<h1>Archived Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Archived at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archived_projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.archived_at %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Archived:</strong>
  <%= @project.archived_at || 'No' %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :done %>
    <%= form.check_box :done %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<div>
  <%= link_to "All", action: :index, params: {} %>
  <%= link_to "Done", action: :index, params: {done: 1} %>
  <%= link_to "Undone", action: :index, params: {done: 0} %>
  /
  <%= link_to "Recent updated", action: :index, params: {sort: :updated_at} %>
  <%= link_to "Due date",       action: :index, params: {sort: :due_date} %>
</div>

<table class='tasks'>
  <thead>
    <tr>
      <th>Created/Due</th>
      <th>Title</th>
      <th>Project</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <span title='<%= task.created_at %>'>
            <%= task.created_at.to_date %>
          </span>
          <% if task.due_date %>
            (<%= task.due_date %>)
          <% end %>
        </td>
        <td class='title'>
          <% if task.done %>&#x2714;<% end %>
          <%= link_to task.title, task %>
        </td>
        <td><%= task.project&.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%=raw pagy_nav(@pagy) %>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/main.html.erb
<div id='ovto-view'></div>
<div id='ovto-debug'></div>

<%= opal_tag do %>
  MyApp.run(id: 'ovto-view')
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= check_box_tag :remember, params[:remember], true %>
    <%= label_tag :remember %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to "Logout", :logout, method: :post %>